# Generated by Django 4.0.3 on 2022-05-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(default='123', max_length=5, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedVoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('to', models.CharField(max_length=4)),
                ('source', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceVoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('file', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TotalNumberOfConverts',
            fields=[
                ('id', models.CharField(default='123', max_length=5, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
