# Generated by Django 4.0.3 on 2022-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceConversion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
